### ISSUE TITLE
Dragging parent COMP doesn't add pars to manager

### ISSUE THREAD

**Issue by function-store** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#17]
1. Have a Base COMP with Custom Params
2. Have TauCeti Preset Manager inside the Base COMP
3. Open the viewer of the manager
4. Navigate to the level of the Base COMP
5. Drag and drop the Base COMP onto the manager
6. ---> Custom Pars are not added to the manager

**Comment by AlphaMoonbaseBerlin** [comment]
This seems to be an issue with the TD drag and drop behavior. I assume it is set up in a way where it keeps a component from being dropped in to itself. (The little + next to the drop arrow is missing in this scenario.)

**Comment by AlphaMoonbaseBerlin** [comment]
https://github.com/AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem/commit/82819551cc8fce3a0b6dbbb27ae3009f06f12e2d

I put in the new drag and drop callback system. Had to handle pargroups though (and seems like everything is a pargroup now? pffft.)
This resolves the issue!
