### ISSUE TITLE
Preset doesn't overwrite

### ISSUE THREAD

**Issue by function-store** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#18]
Instead it creates a new preset with the same name. Previously it used to overwrite, and now this functionality is missing.

**Comment by AlphaMoonbaseBerlin** [comment]
Yeah, def an oversight. Right now you can change the ID Mode to "name" instead of UUID. This generates the ID for the preset based on the name on not randomly on record!

**Comment by AlphaMoonbaseBerlin** [comment]
https://github.com/AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem/commit/ed5f650c12839f9de3be5509da8f5183b8074c61

You can select the wanted behaviour in the Handle Override Parameter.
Override: Simple override. Nothing less.
Request: UI Element opping up requesting input.
Exception: Throw an exception.
