### ISSUE TITLE
COMP/OP type params undesired behavior

### ISSUE THREAD

**Issue by function-store** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#19]
COMP/OP type params get replaced with an absolute path, regardless of `Path Relation`. I would suggest not messing with those fields and just recalling the raw value.

This is the same for v3 by the way.

**Comment by function-store** [comment]
Just to stress why this is important, reflecting to the idea of having the manager inside the comps I want to move around and use relative paths. Replacing relative paths with absolute upon recalling a preset totally breaks this.

**Comment by function-store** [comment]
To add to this, having an expression parMode reference to another OP also gets recalled as an absolute path

**Comment by AlphaMoonbaseBerlin** [comment]
https://github.com/AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem/commit/2b29beef47a54451bb5e7ffb17caa3b7c0021e18

Should be fixed now. Added new parser for OP-Sytel parameters.
