### ISSUE TITLE
Only ONE parameter updated

### ISSUE THREAD

**Issue by stonike-tm** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#20]
I use the preset manager for an other preset a few month ago and I try to use it again.

When I add multiple parameter, only the last parameter is updated ...

Did I miss something ?

**Comment by stonike-tm** [comment]
So I don't understand why, I always have the same Tween Id.

'''Info Header Start
Name : extTweener
Author : Wieland@AMB-ZEPH15
Saveorigin : Project.toe
Saveversion : 2022.32660
Info Header End'''

On Tweener/extTweener , line 124, I change ;
               #self.Tweens[id or self.getFadeId( parameter )] = fadeObject
		self.Tweens[self.getFadeId( parameter )] = fadeObject

**Comment by AlphaMoonbaseBerlin** [comment]
Hoi. 
I have a hard time following you.
Can you please explain exactly which steps you took, what behaviour you expect and which behaviour you got?
Can you maybe upload a simple example project?

Regarding your second Post: Please do not change anything. The System is set up in a way that works. Changing anything in there (esp. if it is the tweener, which is not part of the TauCeti Engine) will not help finding issues.

**Comment by stonike-tm** [comment]
Sorry I don't know what I was doing yesterday.

I do a new test today and it work directly, out the box, like a charm.

Sorry for this issue.

**Comment by AlphaMoonbaseBerlin** [comment]
No worries. 
There are some things weird with a TweenerUpdate I pushed recently which I revoked just this morning, It might have been the reason for your issue to.

Next time please just make sure to create a reporudcable case for me ! Otherwise I am not able to help!
