### ISSUE TITLE
preset_Cuelist callbacks not triggering?

### ISSUE THREAD

**Issue by strangerattractor** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#23]
hi there, 

I think I just found out that the callbacks of preset_Cuelist are not triggering.
Or am I missing something?

Cheers
Max

**Comment by AlphaMoonbaseBerlin** [comment]
@strangerattractor Quick check and they seem to work correctly.
![grafik](https://github.com/user-attachments/assets/3afb94ea-5d13-4595-bafe-66376b1e5b95)
Which version are you on?

**Comment by strangerattractor** [comment]
I was using the 4.15 release
The 4.18 suspect works fine, just tested that.

**Comment by AlphaMoonbaseBerlin** [comment]
I uploaded the 4.18 to the Olib, thanks for the headsup!
