### ISSUE TITLE
Error when loading presetManager in a new project

### ISSUE THREAD

**Issue by mbnzr** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#25]
Hello, 

I immediately get an error when I load the presetManager into the standard project of TD or into an empty project. The plugin is not working, I can fill the stack but cannot record any presets.
I have received a project from someone in which the presetManager is already set up and has been created on a Windows computer. No error is displayed when loading and the plugin is fully functional.

**This is the error before I create a presetfolder:**

![presetManager error before creating presetfolder](https://github.com/user-attachments/assets/c9cf2868-52b6-490a-89ed-6b4c9a1361d5)

**This is the error after I create a presetfolder:**

![presetManager error after creating presetfolder](https://github.com/user-attachments/assets/058e53c0-fb80-4d1a-a747-0be671802042)

**System information:**

OS: Mac OS Sonoma 14.4.1 @ Apple M2 Pro
TD: v2023.12000, non-commercial
PresetManager: v4.44

**Thank you,
Michael**

**Comment by AlphaMoonbaseBerlin** [comment]
Hey @mbnzr , thanks for the report.
This is a MacOS issue, so interrestig that this only popped up now, but as I am not a MacOS user I could not test this.
Can you please test the latest component in the releasefolder?

**Comment by mbnzr** [comment]
Hey @AlphaMoonbaseBerlin ,

thank you so much for the fast reply and fix. I just tried it on my machine and it loads without any errors now.

Cheers,
Michael
