### ISSUE TITLE
Throws Error in 2023.11760

### ISSUE THREAD

**Issue by MXZEHN** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#26]
Throws error when drag and drop in above version. Recent Preset Manager already there.
Downloaded just now, Version 4, build 56
![Dahsboard_error1](https://github.com/user-attachments/assets/bbf6a797-bec5-4ad4-87d5-c6257f2bd2f6)
![Dahsboard_error2](https://github.com/user-attachments/assets/b2e135f7-c195-4e4f-bb84-ccd95d6bddcb)
![Error](https://github.com/user-attachments/assets/8ccabff7-71a4-45df-a44c-d3b555ead068)

Thank you
Best
Stefan

**Comment by AlphaMoonbaseBerlin** [comment]
@MXZEHN 
Please check if this version works
https://github.com/AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem/blob/main/modules/release/preset_Dashboard.tox

Otherwise this is a widgetError that started occuring in transition from 2022 - 2023. I updated the widget.

**Comment by MXZEHN** [comment]
Thank you for the quick fix, this one opens without error message.
Functionality testing during today, will let you know if something comes up...
Best
Stefan
